name: Check dependencies


on:
  push:
  pull_request:
    types:
      - closed
    branches:
      - master


jobs:
  build:
    strategy:
      matrix:
        os: [
          macos-latest,
          windows-latest,
          ubuntu-latest
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
            python-version: 3.9

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies for Windows
        if: matrix.os == 'windows-latest'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip3 install torch torchvision torchaudio torchtext

      - name: Install dependencies for Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip3 install torch torchvision torchaudio torchtext --index-url https://download.pytorch.org/whl/cpu

      - name: Install dependencies for MacOS
        if: matrix.os == 'macos-latest'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip3 install torch torchvision torchaudio torchtext

      - name: Show dependencies
        run: pip list

      - name: Run make_dataset.py
        run: python src/data/make_dataset.py

      - name: Run visualize.py
        run: python src/visualization/visualize.py
